/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Driver */

#ifndef _Included_Driver
#define _Included_Driver
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Driver
 * Method:    sayHello
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_Driver_sayHello
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
