FROM ubuntu:18.04
MAINTAINER adolphusenvy

USER root
ENV DISPLAY :0

RUN apt-get update && \
    apt-get -y install software-properties-common && \
    add-apt-repository -y ppa:webupd8team/java && \
    echo debconf shared/accepted-oracle-license-v1-1 select true | debconf-set-selections && \
    echo debconf shared/accepted-oracle-license-v1-1 seen true | debconf-set-selections && \
    apt-get update && \
    apt-get -y install openjdk-8-jdk git dos2unix net-tools


COPY lib/* /lib/
COPY ibis-run .

RUN git clone https://github.com/AdolphusEnvy/Master-thesis-project.git && \ 
    cd Master-thesis-project/Ibis-application && \
    ls && \
    # sed $'s/\r$//' ./gradlew > ./gradlew.unix && \
    chmod 777 gradlew && \
    dos2unix gradlew && \
    ./gradlew

# CMD  ["./ibis-run"]