FROM ubuntu:18.04
MAINTAINER adolphusenvy

USER root
ENV DISPLAY :0

RUN apt-get update && \
    apt-get -y install software-properties-common && \
    add-apt-repository -y ppa:webupd8team/java && \
    echo debconf shared/accepted-oracle-license-v1-1 select true | debconf-set-selections && \
    echo debconf shared/accepted-oracle-license-v1-1 seen true | debconf-set-selections && \
    apt-get update && \
    apt-get -y install openjdk-8-jdk && \
    apt-get install git

