#!/bin/sh

# This script is a convenience script to start the ipl registry server from the
# IPL installation, specified in the $IPL_HOME environment variable.
# shellcheck disable=SC2155

# Check IPL_HOME.
if [ -z "$DYNPRVDRIVER_HOME" ];  then
    echo "please set DYNPRVDRIVER_HOME to the location of your Ibis installation" 1>&2
    exit 1
fi

exec singularity instance start "$DYNPRVDRIVER_HOME"/DynPrvServer.simg server
