#!/bin/sh
sbatch --nodes=$1 -t -$2 sleepme 30000

JobId=261313 JobName=Calibration
   UserId=yhu310(2362) GroupId=yhu310(2362) MCS_label=N/A
   Priority=4294738626 Nice=0 Account=yhu310 QOS=normal
   JobState=RUNNING Reason=None Dependency=(null)
   Requeue=1 Restarts=0 BatchFlag=1 Reboot=0 ExitCode=0:0
   DerivedExitCode=0:0
   RunTime=01:24:32 TimeLimit=UNLIMITED TimeMin=N/A
   SubmitTime=2020-07-21T09:04:02 EligibleTime=2020-07-21T09:04:02
   StartTime=2020-07-21T09:04:02 EndTime=Unknown Deadline=N/A
   PreemptTime=None SuspendTime=None SecsPreSuspend=0
   Partition=defq AllocNode:Sid=fs1:28626
   ReqNodeList=(null) ExcNodeList=(null)
   NodeList=node102
   BatchHost=node102
   NumNodes=1 NumCPUs=32 NumTasks=1 CPUs/Task=1 ReqB:S:C:T=0:0:*:*
   TRES=cpu=32,node=1
   Socks/Node=* NtasksPerN:B:S:C=0:0:*:* CoreSpec=*
     Nodes=node102 CPU_IDs=0-31 Mem=0 GRES_IDX=
   MinCPUsNode=1 MinMemoryNode=0 MinTmpDiskNode=0
   Features=(null) DelayBoot=00:00:00
   Gres=(null) Reservation=(null)
   OverSubscribe=NO Contiguous=0 Licenses=(null) Network=(null)
   Command=(null)
   WorkDir=/home/yhu310/DynPrvDriver
   StdErr=/home/yhu310/scratch/log/1595315041937.err
   StdIn=/dev/null
   StdOut=/home/yhu310/scratch/log/1595315041937.out
   Power=
   BatchScript=
#!/bin/sh
#SBATCH --job-name='xenon'
#SBATCH -D '/home/yhu310/DynPrvDriver'
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=1
#SBATCH --time=15
#SBATCH --output='/home/yhu310/scratch/log/1595315041937.out'
#SBATCH --error='/home/yhu310/scratch/log/1595315041937.err'
#SBATCH -p defq -J Calibration -t UNLIMITED
export DYNPRVDRIVER_HOME="/home/yhu310/DynPrvDriver"

/home/yhu310/DynPrvDriver/scripts/ipl-run


